import json
import shutil
from datetime import datetime
from pathlib import Path

import joblib
import numpy as np
from sklearn.dummy import DummyClassifier


BASE_DIR = Path(__file__).resolve().parent
MODEL_PATH = BASE_DIR / "model.joblib"
MODEL_NAME_PATH = BASE_DIR / ".model_name"
MODEL_INFO_PATH = BASE_DIR / "model_info.json"
MODEL_VERSION_DIR = BASE_DIR / "model_versions"
DEMO_MODEL_DIR = BASE_DIR / "demo_models"
LABELS = ("31", "32", "33", "34", "35")


def main() -> None:
    MODEL_VERSION_DIR.mkdir(parents=True, exist_ok=True)
    DEMO_MODEL_DIR.mkdir(parents=True, exist_ok=True)

    good_demo_path = DEMO_MODEL_DIR / "trained_random_forest_upload.joblib"
    if MODEL_PATH.exists() and not good_demo_path.exists():
        shutil.copy2(MODEL_PATH, good_demo_path)
        print(f"Saved current model for Admin upload demo: {good_demo_path}")

    x = np.zeros((len(LABELS), 784), dtype=np.float32)
    y = np.asarray(LABELS, dtype=str)
    model = DummyClassifier(strategy="most_frequent")
    model.fit(x, y)

    output = model.predict_proba(np.zeros((1, 784), dtype=np.float32))
    if output.shape != (1, len(LABELS)):
        raise RuntimeError(f"Weak model output shape is invalid: {output.shape}")

    joblib.dump(model, MODEL_PATH, compress=3)
    shutil.copy2(MODEL_PATH, DEMO_MODEL_DIR / "weak_start_model.joblib")
    MODEL_NAME_PATH.write_text("weak-start-dummy.joblib", encoding="utf-8")
    MODEL_INFO_PATH.write_text(
        json.dumps({
            "version_name": "weak-start-dummy",
            "original_filename": "generated by create_weak_model.py",
            "stored_version_file": "model.joblib",
            "active_model_file": MODEL_PATH.name,
            "uploaded_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "activated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "validation_status": "weak starter model for upload demo",
            "input_shape": "(None, 784)",
            "output_shape": f"(None, {len(LABELS)})",
            "test_output_shape": str(tuple(output.shape)),
            "expected_input": "(1, 784)",
            "expected_classes": str(len(LABELS)),
        }, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"Created weak starter model: {MODEL_PATH}")
    print("Upload demo_models/trained_random_forest_upload.joblib when you want to show improvement.")


if __name__ == "__main__":
    main()
